version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/
volumes:
  db-data:
